name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.300'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'AzureSearchQueryBuilder.*/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'AzureSearchQueryBuilder/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'AzureSearchQueryBuilder.Tests/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'AzureSearchQueryBuilder/*.csproj'
    arguments: '--configuration Release --output $(build.artifactstagingdirectory)'
